name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install cargo-xdk
        run: cargo install cargo-xdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew assembleDebug
          ./gradlew cargoBuild || true  # Continue even if cargoBuild fails

      - name: Archive APK artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: ${{ github.workspace }}/app/build/outputs/apk/debug/*.apk
